// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihucnqwrvhjoialhswgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodWNucXdydmhqb2lhbGhzd2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjE0MDksImV4cCI6MjA3NDE5NzQwOX0.epzWWKYFun5WMv2rCY1IvfuTGrUAkXAfcbyBeIYn1ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});